### PR TITLE
Usage docs

### PR DESCRIPTION
**Pull request by valyagolev**
Big fan of the project! But no docs at all? I wrote some stuff down for the next person – or for myself in a month when I forget how to use it.

P.S. I had to vendor it because I'm using pipenv, not poetry – any chance at simply using neither for maximum support?

### CODE REVIEW

**Comment by joaodaher** [comment]
@valyagolev , Thanks for the contribution, the project is quite new and it's been used internally only, it could really use more docs.d
You should be able to install it normally since it's in [Pypi](https://pypi.org/project/django-google-cloud-tasks/):

`pip install django-google-cloud-tasks` should do the trick.

**Comment by valyagolev** [comment]
Yeah, feel free to merge the docs I wrote, why not?

**Comment by thclark** [comment]
Hey @joaodaher I'm absolutely loving this project, what a hero! It'd be great to get this merged though, it'd make it much easier to figure out :)

**Comment by valyagolev** [comment]
i regret that i wasted my time figuring out and writing those docs. it's one click of a button to merge it. whatever

**Comment by thclark** [comment]
Argh @valyagolev it was really helpful to have it left open, people like me won’t find it if the PR is closed.

**Comment by valyagolev** [comment]
@thclark  feel free to use my fork https://github.com/valyagolev/django-cloud-tasks

**Comment by thclark** [comment]
Thanks @valyagolev I will!!

**Pull request closed without merging**
